name: DungeonFighters
main: de.bergwerklabs.dungeonfighters.DungeonFightersPlugin
website: http://www.bergwerklabs.de
author: Freggy
version: 1.0
depend: [LABS_Util, LabsFrameworkSpigotCommons]

commands:
    money:
    feuerfrei: