package de.bergwerklabs.dungeonfighters.game.map;

import de.bergwerklabs.fmga.algorithm.grid.GridCoordinate;
import de.bergwerklabs.fmga.algorithm.module.ModuleType;
import de.bergwerklabs.framework.schematicservice.LabsSchematic;

import java.io.File;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Created by Yannic Rieger on 30.05.2017.
 * <p>  </p>
 *
 * @author Yannic Rieger
 */
public class Dungeon {

    /**
     * Map containing all the modules.
     */
    public HashMap<ModuleType, List<LabsSchematic>> getModules() { return this.modules; }

    /**
     * Dungeon generated by FMGA.
     */
    public GridCoordinate[][] getGrid() {
        return grid;
    }

    private HashMap<ModuleType, List<LabsSchematic>> modules = new HashMap<>();
    private GridCoordinate[][] grid;

    /**
     * @param mapFolder Folder in which the  map specific schematics are located.
     */
    public Dungeon(File mapFolder, GridCoordinate[][] grid) {
        this.grid = grid;
        List<File> modules = Arrays.asList(mapFolder.listFiles());
        this.modules.put(ModuleType.HORIZONTAL_PASSAGE, this.getSchematicList(modules, ModuleType.HORIZONTAL_PASSAGE.name()));
        this.modules.put(ModuleType.CROSS_CONNECTION,   this.getSchematicList(modules, ModuleType.CROSS_CONNECTION.name()));
        this.modules.put(ModuleType.L_LEFT_DOWN,        this.getSchematicList(modules, ModuleType.L_LEFT_DOWN.name()));
        this.modules.put(ModuleType.L_LEFT_UP,          this.getSchematicList(modules, ModuleType.L_LEFT_UP.name()));
        this.modules.put(ModuleType.L_RIGHT_DOWN,       this.getSchematicList(modules, ModuleType.L_RIGHT_DOWN.name()));
        this.modules.put(ModuleType.L_RIGHT_UP,         this.getSchematicList(modules, ModuleType.L_RIGHT_UP.name()));
        this.modules.put(ModuleType.T_DOWN,             this.getSchematicList(modules, ModuleType.T_DOWN.name()));
        this.modules.put(ModuleType.T_LEFT,             this.getSchematicList(modules, ModuleType.T_LEFT.name()));
        this.modules.put(ModuleType.T_RIGHT,            this.getSchematicList(modules, ModuleType.T_RIGHT.name()));
        this.modules.put(ModuleType.T_UP,               this.getSchematicList(modules, ModuleType.T_UP.name()));
        this.modules.put(ModuleType.VERTICAL_PASSAGE,   this.getSchematicList(modules, ModuleType.VERTICAL_PASSAGE.name()));
    }

    /**
     * Gets the list of schematics based of the module type.
     * @param modules Schematics as files
     * @param moduleType ModuleType
     * @return the list of schematics based of the module type.
     */
    private List<LabsSchematic> getSchematicList(List<File> modules, String moduleType) {
        return modules.stream().filter(file -> file.getName().endsWith(moduleType))
                      .map(file -> new LabsSchematic(file))
                      .collect(Collectors.toList());
    }
}
