package de.bergwerklabs.dungeonfighters.game.map;

import de.bergwerklabs.framework.schematicservice.LabsSchematic;

import java.io.File;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Created by Yannic Rieger on 30.05.2017.
 * <p>  </p>
 *
 * @author Yannic Rieger
 */
public class Dungeon {

    /**
     * Map containing all the modules.
     */
    public HashMap<String, List<LabsSchematic>> getModules() { return this.modules; }

    /**
     * Dungeon generated by FMGA.
     */
    public Integer[][] getGrid() {
        return grid;
    }

    private HashMap<String, List<LabsSchematic>> modules = new HashMap<>();
    private Integer[][] grid;

    // TODO: add FMGA dungeon layout

    /**
     * @param mapFolder Folder in which the  map specific schematics are located.
     */
    public Dungeon(File mapFolder) {
        this.grid = new Integer[10][10];
        List<File> modules = Arrays.asList(mapFolder.listFiles());
        this.modules.put("HORIZONTAL_PASSAGE", this.getSchematicList(modules, "HORIZONTAL_PASSAGE"));
        this.modules.put("HORIZONTAL_PASSAGE", this.getSchematicList(modules, "HORIZONTAL_PASSAGE"));
        this.modules.put("HORIZONTAL_PASSAGE", this.getSchematicList(modules, "HORIZONTAL_PASSAGE"));
        this.modules.put("HORIZONTAL_PASSAGE", this.getSchematicList(modules, "HORIZONTAL_PASSAGE"));
        this.modules.put("HORIZONTAL_PASSAGE", this.getSchematicList(modules, "HORIZONTAL_PASSAGE"));
        this.modules.put("HORIZONTAL_PASSAGE", this.getSchematicList(modules, "HORIZONTAL_PASSAGE"));
        this.modules.put("HORIZONTAL_PASSAGE", this.getSchematicList(modules, "HORIZONTAL_PASSAGE"));
        this.modules.put("HORIZONTAL_PASSAGE", this.getSchematicList(modules, "HORIZONTAL_PASSAGE"));
        this.modules.put("HORIZONTAL_PASSAGE", this.getSchematicList(modules, "HORIZONTAL_PASSAGE"));
        this.modules.put("HORIZONTAL_PASSAGE", this.getSchematicList(modules, "HORIZONTAL_PASSAGE"));
        this.modules.put("HORIZONTAL_PASSAGE", this.getSchematicList(modules, "HORIZONTAL_PASSAGE"));
    }

    /**
     * Gets the list of schematics based of the module type.
     * @param modules Schematics as files
     * @param moduleType ModuleType
     * @return the list of schematics based of the module type.
     */
    private List<LabsSchematic> getSchematicList(List<File> modules, String moduleType) {
        return modules.stream().filter(file -> file.getName().endsWith(moduleType))
                      .map(file -> new LabsSchematic(file))
                      .collect(Collectors.toList());
    }
}
