name: DungeonFighters
main: de.bergwerklabs.dungeonfighters.dungeongames.jnr.DungeonJumpAndRun
website: http://www.bergwerklabs.de
author: Freggy
version: 1.0
depend: [LabsFrameworkSpigotCommons, DungeonFighters]