package de.bergwerklabs.dungeonfighters.game.core;

import com.google.gson.JsonObject;
import de.bergwerklabs.dungeonfighters.api.game.DungeonMechanicProvider;
import de.bergwerklabs.dungeonfighters.game.core.arena.fubar.TileType;
import de.bergwerklabs.dungeonfighters.game.core.games.map.DungeonGameWrapper;
import de.bergwerklabs.framework.schematicservice.LabsSchematic;
import org.bukkit.ChunkSnapshot;
import org.bukkit.util.Vector;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Created by Yannic Rieger on 30.05.2017.
 * <p>  </p>
 *
 * @author Yannic Rieger
 */
public class Dungeon {

    /**
     * Map containing all the modules.
     */
    public HashMap<TileType, List<LabsSchematic>> getModules() { return this.modules; }

    public HashMap<ChunkSnapshot, DungeonMechanicProvider> getGamePositions() { return this.gamePositions; }

    public HashMap<DungeonMechanicProvider, Integer> getGetModuleLength() { return this.moduleLengths; }

    /**
     * Gets the list of available {@link DungeonGameWrapper}s.
     */
    public List<DungeonGameWrapper> getDungeonGames() { return this.dungeonGames; }

    /**
     * Gets the list of start point schematics for this dungeon.
     */
    public List<File> getStartPoints() { return this.startPoints; }

    /**
     * Gets the list of end point schematics for this dungeon.
     */
    public List<File> getEndPoints() { return this.endPoints; }

    /**
     * Dungeon generated by FUBAR.
     */
    public TileType[] getGrid() {
        return grid;
    }

    private HashMap<TileType, List<LabsSchematic>> modules = new HashMap<>();
    private HashMap<ChunkSnapshot, DungeonMechanicProvider> gamePositions = new HashMap<>();
    private HashMap<DungeonMechanicProvider, Integer> moduleLengths = new HashMap<>();
    private List<DungeonGameWrapper> dungeonGames = new ArrayList<>();
    private List<File> startPoints;
    private List<File> endPoints;
    private TileType[] grid;


    /**
     *
     * @param gamesFolder
     * @param startPoints
     * @param endPoints
     * @param grid
     */
    public Dungeon(List<File> gamesFolder, List<File> startPoints, List<File> endPoints, TileType[] grid) {
        //this.grid = grid;
        //this.loadMapTiles(mapFolder);
        this.loadGames(gamesFolder, startPoints, endPoints);
    }

    /**
     * Loads and assigns all the {@link LabsSchematic}s for the matching {@link TileType}.
     *
     * @param mapFolder Folder where the {@link LabsSchematic}s are located.
     */
    private void loadMapTiles(File mapFolder) {
        List<File> modules = Arrays.asList(mapFolder.listFiles());
        this.modules.put(TileType.STRAIGHT_HORIZONTAL, this.getSchematicList(modules, TileType.STRAIGHT_HORIZONTAL.name()));
        this.modules.put(TileType.STRAIGHT_VERTICAL,   this.getSchematicList(modules, TileType.STRAIGHT_VERTICAL.name()));
        this.modules.put(TileType.CROSS,               this.getSchematicList(modules, TileType.CROSS.name()));
        this.modules.put(TileType.CORNER_RIGHT_DOWN,   this.getSchematicList(modules, TileType.CORNER_RIGHT_DOWN.name()));
        this.modules.put(TileType.CORNER_LEFT_UP,      this.getSchematicList(modules, TileType.CORNER_LEFT_UP.name()));
        this.modules.put(TileType.CORNER_LEFT_DOWN,    this.getSchematicList(modules, TileType.CORNER_LEFT_DOWN.name()));
        this.modules.put(TileType.CORNER_RIGHT_UP,     this.getSchematicList(modules, TileType.CORNER_RIGHT_UP.name()));
        this.modules.put(TileType.T_DOWN,              this.getSchematicList(modules, "T_D"));
        this.modules.put(TileType.T_LEFT,              this.getSchematicList(modules, "T_L"));
        this.modules.put(TileType.T_RIGHT,             this.getSchematicList(modules, "T_R"));
        this.modules.put(TileType.T_UP,                this.getSchematicList(modules, "T_U"));
        this.modules.put(TileType.END_DOWN,            this.getSchematicList(modules, TileType.END_DOWN.name()));
        this.modules.put(TileType.END_UP,              this.getSchematicList(modules, TileType.END_UP.name()));
        this.modules.put(TileType.END_RIGHT,           this.getSchematicList(modules, TileType.END_RIGHT.name()));
        this.modules.put(TileType.END_LEFT,            this.getSchematicList(modules, TileType.END_LEFT.name()));
    }

    /**
     * Loads all the {@link DungeonGameWrapper}s.
     */
    private void loadGames(List<File> gamesFolder, List<File> startPoints, List<File> endPoints) {
       for (File gameFolder : gamesFolder) {
           dungeonGames.add(this.createGame(gameFolder));
       }


       this.startPoints = startPoints;
       this.endPoints = endPoints;
    }

    /**
     * Creates {@link DungeonGameWrapper} with all the needed files.
     *
     * @param gameFolder Folder where plugin jar and module folders are contained.
     * @return a {@link DungeonGameWrapper}
     */
    private DungeonGameWrapper createGame(File gameFolder) {
        return new DungeonGameWrapper(new File(gameFolder.getPath() + gameFolder.getName() + ".jar"), Arrays.asList(gameFolder.listFiles()));
    }

    /**
     * Deserializes a {@link Vector}.
     *
     * @param object {@link JsonObject} containing x, y and z coordinates.
     * @return a {@link Vector}
     */
    private Vector deserializeVector(JsonObject object) {
        return new Vector(object.get("x").getAsDouble(), object.get("y").getAsDouble(), object.get("z").getAsDouble());
    }

    /**
     * Gets the list of schematics based of the module type.
     *
     * @param modules Schematics as files
     * @param moduleType ModuleType
     * @return the list of schematics based of the module type.
     */
    private List<LabsSchematic> getSchematicList(List<File> modules, String moduleType) {
        return modules.stream().filter(file -> file.getName().endsWith(moduleType + ".schematic"))
                      .map(LabsSchematic::new)
                      .collect(Collectors.toList());
    }
}
